package com.stefanini.model;
// Generated 07/11/2016 12:03:46 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "hackathon")
public class Modelo implements java.io.Serializable {

	private static final long serialVersionUID = -294635175633524077L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idModelo", unique = true, nullable = false)
	private Integer idModelo;
	
	@OneToOne
	@JoinColumn(name = "idCategoria", nullable = false)
	private Categoria categoria;
	
	@Column(name = "descricaoModelo", length = 50)
	private String descricaoModelo;

	public Modelo() {
	}

	public Integer getIdModelo() {
		return idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getDescricaoModelo() {
		return descricaoModelo;
	}

	public void setDescricaoModelo(String descricaoModelo) {
		this.descricaoModelo = descricaoModelo;
	}
	
}
